version: "3"

services:
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
#                     C O D E I G N I T E R  v4.2.3                        #
#--------------------------------------------------------------------------#
#--------------------------------------------------------------------------#
    codeigniter4:
        image: atsanna/codeigniter4:latest
#        image: atsanna/codeigniter4:v4.2.3-php8.1-apache
#        image: atsanna/codeigniter4:v4.2.3-php8.1.9-apache
#        image: atsanna/codeigniter4:v4.2.3-php8.0-apache
#        image: atsanna/codeigniter4:v4.2.3-php8.0.20-apache
#        image: atsanna/codeigniter4:v4.2.3-php7.4-apache
#        image: atsanna/codeigniter4:v4.2.3-php7.4.30-apache
        container_name: 'codeigniter4'
        environment:
          - REGEN_ENV_FILE=1

          - CI_ENVIRONMENT=development
          - APP_BASE_URL=https://${PROJECT_BASE_URL}/
          - DB_DEFAULT_HOSTNAME=${MYSQL_HOSTNAME}
          - DB_DEFAULT_DATABASE=${MYSQL_DATABASE}
          - DB_DEFAULT_USERNAME=${MYSQL_USER}
          - DB_DEFAULT_PASSWORD=${MYSQL_PASSWORD}
          - DB_DEFAULT_DRIVER=MySQLi
          - DB_DEFAULT_PORT=3306

          - ROOT_EMAIL=${EMAIL_ROOT}
          - MAIL_SERVER=${MAIL_SERVER}
          - MAIL_SERVER_PORT=${MAIL_SERVER_PORT}
          - MAIL_SERVER_USER=${MAIL_SERVER_USER}
          - MAIL_SERVER_PASSWORD=${MAIL_SERVER_PASSWORD}
          - MAIL_SERVER_TLS=${MAIL_SERVER_TLS}
          - MAIL_SERVER_STARTTLS=${MAIL_SERVER_STARTTLS}
        ports:
          - 80:80
        links:
          - codeigniter4_mysql
        volumes:
          - ./localfolder/www:/var/www/html
